import { CustomFieldConfig, LanguageCode } from '@vendure/core';

export const contentCustomFields: CustomFieldConfig[] = [
  {
    name: 'supportEmail',
    type: 'string',
    label: [{ languageCode: LanguageCode.en, value: 'Support Email' }],
    description: [{ languageCode: LanguageCode.en, value: 'Email address for customer support inquiries' }],
    defaultValue: 'soporte@kaostore.com',
    ui: { component: 'text-form-input' },
  },
  {
    name: 'contactEmail',
    type: 'string',
    label: [{ languageCode: LanguageCode.en, value: 'Contact Email' }],
    description: [{ languageCode: LanguageCode.en, value: 'General contact email address' }],
    defaultValue: 'contacto@kaostore.com',
    ui: { component: 'text-form-input' },
  },
  {
    name: 'aboutUs',
    type: 'text',
    label: [{ languageCode: LanguageCode.en, value: 'About Us Content' }],
    description: [{ languageCode: LanguageCode.en, value: 'Company story and mission statement' }],
    ui: { component: 'rich-text-form-input' },
  },
  {
    name: 'shippingPolicy',
    type: 'text',
    label: [{ languageCode: LanguageCode.en, value: 'Shipping Policy' }],
    description: [{ languageCode: LanguageCode.en, value: 'Shipping times, costs, and policies' }],
    ui: { component: 'rich-text-form-input' },
  },
  {
    name: 'returnPolicy',
    type: 'text',
    label: [{ languageCode: LanguageCode.en, value: 'Return Policy' }],
    description: [{ languageCode: LanguageCode.en, value: 'Return and refund policies' }],
    ui: { component: 'rich-text-form-input' },
  },
  {
    name: 'faqContent',
    type: 'text',
    label: [{ languageCode: LanguageCode.en, value: 'FAQ Content (JSON)' }],
    description: [{ languageCode: LanguageCode.en, value: 'FAQ items in JSON format' }],
    ui: { component: 'json-editor-form-input' },
  },
  {
    name: 'legalContent',
    type: 'text',
    label: [{ languageCode: LanguageCode.en, value: 'Legal/Terms Content' }],
    description: [{ languageCode: LanguageCode.en, value: 'Terms of service and legal information' }],
    ui: { component: 'rich-text-form-input' },
  },
  {
    name: 'privacyPolicy',
    type: 'text',
    label: [{ languageCode: LanguageCode.en, value: 'Privacy Policy' }],
    description: [{ languageCode: LanguageCode.en, value: 'Privacy policy content' }],
    ui: { component: 'rich-text-form-input' },
  },
  {
    name: 'termsOfService',
    type: 'text',
    label: [{ languageCode: LanguageCode.en, value: 'Terms of Service' }],
    description: [{ languageCode: LanguageCode.en, value: 'Terms of service content' }],
    ui: { component: 'rich-text-form-input' },
  },
  {
    name: 'socialMediaFacebook',
    type: 'string',
    label: [{ languageCode: LanguageCode.en, value: 'Facebook URL' }],
    description: [{ languageCode: LanguageCode.en, value: 'Facebook page URL' }],
    ui: { component: 'text-form-input' },
  },
  {
    name: 'socialMediaInstagram',
    type: 'string',
    label: [{ languageCode: LanguageCode.en, value: 'Instagram URL' }],
    description: [{ languageCode: LanguageCode.en, value: 'Instagram profile URL' }],
    ui: { component: 'text-form-input' },
  },
  {
    name: 'socialMediaTwitter',
    type: 'string',
    label: [{ languageCode: LanguageCode.en, value: 'Twitter URL' }],
    description: [{ languageCode: LanguageCode.en, value: 'Twitter profile URL' }],
    ui: { component: 'text-form-input' },
  },
];
